# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a979a66c073e63fbe04cd1c9e5c5397344b0e99552aad17d399b4c3da09e2dacffeaf87eb069b8552b082430a311555155be5724d8a53494db76fd53f420050a
  # facebook_secret: d6b3b38bb4c9d2af2e0454764507ebf9
  # facebook_key: '540616422783926'

test:
  secret_key_base: 882d43cc5c8f3043cb11dec78fc7626379e98ac7b27bdc405aac0aba36e8911e081f24c8b175b5e2b79ca30fd4d51678c743bc36909b3d3b69d1d848d287f1b0
  # facebook_secret: d6b3b38bb4c9d2af2e0454764507ebf9
  # facebook_key: '540616422783926'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  # facebook_key: <%= ENV["FACEBOOK_KEY"] %>
